version: "3.8"

services:
  backend:
    build: ./backend
    ports:
      - "9000:9000"
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    depends_on:
      - net yet
  frontend:
    build: ./frontend

volumes:
  logs:
